apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: todo
spec:
  ports:
    - port: 80
      targetPort: 3500
      nodePort: 35000
      protocol: TCP
  type: NodePort
  selector:
    role: api
